Lesson16 Postgre&Deploy
qagushaq/TestGuru pull request #16
Opened 2021-04-26 14:11 UTC by qagushaq

2021-04-28 19:25 UTC, BubuntuClu requested changes

2021-04-28 19:25 UTC, BubuntuClu commented on config/routes.rb
> +  post '/feedbacks/new', to: 'feedbacks#new'
это что за? с каких пор `new` идет как `post`? убери это

2021-04-29 14:19 UTC, BubuntuClu requested changes

2021-04-29 14:19 UTC, BubuntuClu commented on app/javascript/utilities/test_passage_answers_check.js
> +    answered = false
зачем тут переменная `answered`?

2021-04-29 14:19 UTC, BubuntuClu commented on app/javascript/utilities/test_passage_answers_check.js
> +document.addEventListener('turbolinks:load', function() {
можно конечно добавить эту проверку и на js, но и на бэке надо это обрабатывать. что ответы пустые

2021-04-29 14:19 UTC, BubuntuClu commented on app/views/admin/answers/new.html.erb
> +<h1><%= t('.newanswer')%></h1>
разделители между словами добавь

2021-04-29 14:19 UTC, BubuntuClu commented on app/controllers/feedbacks_controller.rb
> +    if @feedback..valid?
многоточие

2021-04-29 14:46 UTC, qagushaq commented on app/javascript/utilities/test_passage_answers_check.js
> +    answered = false
потому что я ее в showBtnNext() дергаю)

2021-04-29 20:42 UTC, BubuntuClu commented on app/javascript/utilities/test_passage_answers_check.js
> +    answered = false
а зачем это? может этот метод подставить сразу в `if`? тогда надобность в переменой отпадет

2021-04-29 20:42 UTC, BubuntuClu commented on app/models/feedback.rb
> +  attr_accessor :email, :message
это что за покемон? для чего это тут?

2021-04-30 21:10 UTC, BubuntuClu approved these changes

2021-04-30 21:10 UTC, BubuntuClu commented on app/models/feedback.rb
> +class Feedback < ApplicationRecord
валидация полей пропала. надо проверять что почта и текст заполнены

2021-05-02 18:46 UTC, merged